name = "wedding-website-nextjs"
main = ".open-next/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
minify = true
upload_source_maps = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "auth-js-d1-guest-codes-db"
database_id = "402737a8-2ae9-4412-9fd5-dc85939b5f9f"
